### ISSUE TITLE
Laravel 5.4 compatibility

### ISSUE THREAD

**Issue by tatarko** [hazestudio/laravel-gopay-sdk#1]
Hi, can you please make this library compatible with Laravel 5.4? When I am trying to upgrade it throws me this error [Undefined method Illuminate\Foundation\Application::share()](https://laracasts.com/discuss/channels/laravel/undefined-method-illuminatefoundationapplicationshare-when-upgrading-to-laravel-54) and it should be only one little change in codebase. Thank you in advance ;)

**Comment by dImrich** [comment]
Hello @tatarko,
now package should work on Laravel 5.4. I haven't tested it on new laravel, please let me know whether it is working properly.

Run this command for update:
`composer update hazestudio/laravel-gopay-sdk`

Problem was removed share function for connect main class with facade in 5.4
Fixed in commit 87b6aeb6069adf1ecc0cf73a5b9e0e316c4e5d22

Thanks for your issue report :)

**Comment by tatarko** [comment]
Hello @DamianImrich,

it works correctly. Thank you so much for your time fixing this problem and I think that we can now close this issue.
